// SPDX-License-Identifier: AGPL-3.0-only
//
// Rust types for the Zwift relay protobuf schema. Generated by
// `prost-build` from a vendored copy of the upstream zwift-offline
// proto tree (https://github.com/zoffline/zwift-offline).
//
// See docs/plans/STEP-06-proto-crate.md.

include!(concat!(env!("OUT_DIR"), "/_.rs"));
