// SPDX-License-Identifier: AGPL-3.0-only
//
// Rust types for the Zwift relay protobuf schema. Generated by
// `prost-build` from a vendored copy of the upstream zwift-offline
// proto tree (https://github.com/zoffline/zwift-offline).
//
// See docs/plans/STEP-06-proto-crate.md.

pub static FILE_DESCRIPTOR_SET_BYTES: &[u8] =
    include_bytes!(concat!(env!("OUT_DIR"), "/file_descriptor_set.bin"));

include!(concat!(env!("OUT_DIR"), "/_.rs"));
