// SPDX-License-Identifier: AGPL-3.0-only
//
// AES-128-GCM with 4-byte tag. The known-answer test is spec §7.11
// compatibility test #1 — the canned vector below was generated by
// `tests/fixtures/gen_vectors.mjs` against Node's `crypto` API, the
// same one sauce4zwift uses at `zwift.mjs:1092-1106`. See
// `tests/fixtures/README.md` for the regen recipe.

use hex_literal::hex;
use zwift_relay::{CodecError, decrypt, encrypt};

// --- generated by `node gen_vectors.mjs` (node v25.9.0) -----------

const KEY: [u8; 16] = hex!("000102030405060708090a0b0c0d0e0f");
const IV: [u8; 12] = hex!("000000010003004200000001");
const AAD: [u8; 7] = hex!("06deadbeef0042");
const PLAINTEXT: [u8; 5] = hex!("0200102030");
/// `ciphertext (5) || tag (4) = 9 bytes`.
const CIPHER_TAG: [u8; 9] = hex!("20c35150db541dbc33");

// --- known-answer tests --------------------------------------------

#[test]
fn aes_gcm4_encrypt_known_vector() {
    // Spec §7.11 compat test #1: byte-identical to the Node oracle.
    let out = encrypt(&KEY, &IV, &AAD, &PLAINTEXT);
    assert_eq!(
        out, &CIPHER_TAG[..],
        "Rust encrypt output must match the Node oracle byte-for-byte",
    );
}

#[test]
fn aes_gcm4_decrypt_known_vector() {
    let out = decrypt(&KEY, &IV, &AAD, &CIPHER_TAG).expect("decrypt should accept oracle ciphertext");
    assert_eq!(out, &PLAINTEXT[..]);
}

// --- round-trip ----------------------------------------------------

#[test]
fn aes_gcm4_round_trip_random() {
    // 16 deterministic-but-varied (key, iv, aad, plaintext) tuples.
    // No external RNG: each tuple is derived from the iteration index
    // so the test is reproducible on any host.
    for i in 0u8..16 {
        let mut key = [0u8; 16];
        let mut iv = [0u8; 12];
        for (j, byte) in key.iter_mut().enumerate() {
            *byte = i.wrapping_mul(31).wrapping_add(j as u8);
        }
        for (j, byte) in iv.iter_mut().enumerate() {
            *byte = i.wrapping_mul(13).wrapping_add(j as u8);
        }
        let aad: Vec<u8> = (0..(i as usize % 11)).map(|j| j as u8 ^ i).collect();
        let plaintext: Vec<u8> = (0..(1 + (i as usize % 23))).map(|j| (j as u8).wrapping_add(i)).collect();

        let cipher = encrypt(&key, &iv, &aad, &plaintext);
        let recovered = decrypt(&key, &iv, &aad, &cipher).expect("decrypt should round-trip");
        assert_eq!(recovered, plaintext, "iter {i}");
    }
}

// --- tamper rejection ----------------------------------------------

#[test]
fn aes_gcm4_decrypt_rejects_tampered_tag() {
    let mut tampered = CIPHER_TAG;
    // Flip a bit in the 4-byte tag (last 4 bytes of the buffer).
    tampered[CIPHER_TAG.len() - 1] ^= 0x01;
    let err = decrypt(&KEY, &IV, &AAD, &tampered).expect_err("must reject tampered tag");
    assert_eq!(err, CodecError::AuthTagMismatch);
}

#[test]
fn aes_gcm4_decrypt_rejects_tampered_aad() {
    let mut bad_aad = AAD;
    bad_aad[0] ^= 0x01;
    let err = decrypt(&KEY, &IV, &bad_aad, &CIPHER_TAG).expect_err("must reject tampered AAD");
    assert_eq!(err, CodecError::AuthTagMismatch);
}

#[test]
fn aes_gcm4_decrypt_rejects_tampered_ciphertext() {
    let mut tampered = CIPHER_TAG;
    // Flip a bit in the ciphertext body (first byte, well clear of the tag).
    tampered[0] ^= 0x01;
    let err = decrypt(&KEY, &IV, &AAD, &tampered).expect_err("must reject tampered ciphertext");
    assert_eq!(err, CodecError::AuthTagMismatch);
}
