// SPDX-License-Identifier: AGPL-3.0-only
//! 19.5 — Metric parity: raw bytes → decode → ingest → format.
//!
//! Two oracle kinds (per Decision D3 in docs/planning/STEP-19-compatibility-tests.md):
//!
//! - **Synthetic parity oracles** (`constant_power`, `ramp`): hand-derivable
//!   expected values, true ≤ 1e-6 parity. Oracles committed to
//!   `compat/expected/*.metrics.json`, generated by `generate_compat_fixtures`.
//!
//! - **Real-ride regression golden** (`recorded_ride`): ranchero's own output
//!   frozen as `compat/expected/recorded_ride.golden.json`. Asserts stability,
//!   not an independent JavaScript oracle (no JS replay path exists).
//!
//! See docs/planning/STEP-19-compatibility-tests.md, item 19.5.

use std::sync::Arc;
use std::path::Path;

use prost::Message as _;
use serde_json::Value;
use zwift_proto::ServerToClient;
use zwift_relay::capture::{
    CaptureItem, CaptureReader, ContentType, Direction,
};
use ranchero::web::{
    format::format_athlete_data_v1,
    proto_to_stats::route_player_state,
    WebState,
};

use crate::support;

// ---------------------------------------------------------------------------
// Fixture paths
// ---------------------------------------------------------------------------

const FIXTURES_DIR: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/compat/fixtures/server_to_client",
);
const EXPECTED_DIR: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/compat/expected",
);

// ---------------------------------------------------------------------------
// Discovery: every .bin fixture must have a committed oracle
// ---------------------------------------------------------------------------

#[test]
fn all_fixtures_have_oracles() {
    let entries = std::fs::read_dir(FIXTURES_DIR)
        .expect("read fixtures dir");

    for entry in entries {
        let path = entry.expect("dir entry").path();
        let name = path.file_name().unwrap().to_string_lossy().into_owned();
        if !name.ends_with(".bin") {
            continue;
        }
        let stem = name.trim_end_matches(".bin");
        let metrics = format!("{EXPECTED_DIR}/{stem}.metrics.json");
        let golden  = format!("{EXPECTED_DIR}/{stem}.golden.json");
        let has_oracle = Path::new(&metrics).exists() || Path::new(&golden).exists();
        assert!(
            has_oracle,
            "fixture {name} has no oracle: expected either \
             {stem}.metrics.json or {stem}.golden.json in compat/expected/",
        );
    }
}

// ---------------------------------------------------------------------------
// Synthetic parity tests
// ---------------------------------------------------------------------------

#[test]
fn constant_power_metrics_match_oracle() {
    let bin    = format!("{FIXTURES_DIR}/constant_power.bin");
    let oracle = format!("{EXPECTED_DIR}/constant_power.metrics.json");
    let actual = run_pipeline(&bin);
    let golden = load_json(&oracle);
    support::assert_metric_parity(&actual, &golden);
}

#[test]
fn ramp_metrics_match_oracle() {
    let bin    = format!("{FIXTURES_DIR}/ramp.bin");
    let oracle = format!("{EXPECTED_DIR}/ramp.metrics.json");
    let actual = run_pipeline(&bin);
    let golden = load_json(&oracle);
    support::assert_metric_parity(&actual, &golden);
}

// ---------------------------------------------------------------------------
// Real-ride regression guard
// ---------------------------------------------------------------------------

#[test]
#[ignore = "slow: real recorded ride (206 s of relay telemetry)"]
fn recorded_ride_matches_golden() {
    let bin    = format!("{FIXTURES_DIR}/recorded_ride.bin");
    let golden = format!("{EXPECTED_DIR}/recorded_ride.golden.json");
    let actual = run_pipeline(&bin);
    let oracle = load_json(&golden);
    support::assert_metric_parity(&actual, &oracle);
}

// ---------------------------------------------------------------------------
// Prove each tolerance regime bites
// ---------------------------------------------------------------------------

#[test]
fn float_regime_bites_on_diff_above_threshold() {
    let a = serde_json::json!({"avg": 250.0});
    let g = serde_json::json!({"avg": 250.000002}); // 2e-6 > 1e-6

    let result = std::panic::catch_unwind(|| {
        support::assert_metric_parity(&a, &g);
    });
    assert!(result.is_err(), "assert_metric_parity must fail when float diff > 1e-6");
}

#[test]
fn integer_regime_bites_on_off_by_one() {
    let a = serde_json::json!({"lapCount": 2});
    let g = serde_json::json!({"lapCount": 3});

    let result = std::panic::catch_unwind(|| {
        support::assert_metric_parity(&a, &g);
    });
    assert!(result.is_err(), "assert_metric_parity must fail on integer mismatch");
}

// ---------------------------------------------------------------------------
// Pipeline helper: decode → route → flush → format
// ---------------------------------------------------------------------------

/// Read every ServerToClient frame from `fixture_path`, route each PlayerState
/// through the stats engine, flush deferred buffers, and format all athletes.
///
/// Returns a JSON object keyed by athlete ID string.
fn run_pipeline(fixture_path: &str) -> Value {
    let state = Arc::new(WebState::new());

    let mut reader = CaptureReader::open(fixture_path)
        .unwrap_or_else(|e| panic!("open {fixture_path}: {e}"));

    while let Some(item) = reader.next_item() {
        match item.expect("read capture record") {
            CaptureItem::Manifest(_) => {}
            CaptureItem::Frame(record) => {
                if record.direction != Direction::Inbound {
                    continue;
                }
                if record.content_type != ContentType::ProtobufLite {
                    continue;
                }
                let stc = match ServerToClient::decode(record.payload.as_slice()) {
                    Ok(s)  => s,
                    Err(_) => continue,
                };
                for ps in stc.states.iter().chain(stc.player_states.iter()) {
                    route_player_state(ps, &state, 0.0, 0);
                }
            }
        }
    }

    // Flush deferred buffers so the last tick's data is visible to the formatter.
    {
        let mut reg = state.registry.write().unwrap();
        let ids: Vec<u32> = reg.iter().map(|(id, _)| *id).collect();
        for id in ids {
            if let Some(ad) = reg.get_mut(id) {
                ad.bucket.flush_all();
            }
        }
    }

    let reg = state.registry.read().unwrap();
    let mut map = serde_json::Map::new();
    for (id, athlete) in reg.iter() {
        let json = format_athlete_data_v1(athlete, None, None, None, 0.0, 0.0, None);
        map.insert(id.to_string(), json);
    }
    Value::Object(map)
}

fn load_json(path: &str) -> Value {
    let bytes = std::fs::read(path)
        .unwrap_or_else(|e| panic!("read oracle {path}: {e}"));
    serde_json::from_slice(&bytes)
        .unwrap_or_else(|e| panic!("parse oracle {path}: {e}"))
}
