// SPDX-License-Identifier: AGPL-3.0-only
//! 19.2 — AES-GCM interop, workspace-root entry point.
//!
//! Pins the same known-answer vector as
//! `crates/zwift-relay/tests/crypto.rs::aes_gcm4_encrypt_known_vector` /
//! `aes_gcm4_decrypt_known_vector`, generated by
//! `crates/zwift-relay/tests/fixtures/gen_vectors.mjs` against Node's
//! `crypto` API (the same implementation used by sauce4zwift).
//!
//! This file is the discoverable workspace-root entry point for spec §7.11
//! compatibility test #1.  The canonical pin lives in the crate test; this
//! test re-asserts it so that `cargo test` at the root reports it alongside
//! the other compat tests.
//!
//! See docs/planning/STEP-19-compatibility-tests.md, item 19.2.

use zwift_relay::{decrypt, encrypt};

// Vector generated by `node crates/zwift-relay/tests/fixtures/gen_vectors.mjs`
// (Node v25.9.0).  Do not change these constants without regenerating via the
// same script and updating the canonical pin in crates/zwift-relay/tests/crypto.rs.
//
// KEY  = 000102030405060708090a0b0c0d0e0f
// IV   = 000000010003004200000001
// AAD  = 06deadbeef0042
// PT   = 0200102030
// CT+T = 20c35150db541dbc33  (5-byte ciphertext || 4-byte GCM tag)

const KEY:        [u8; 16] = [0x00,0x01,0x02,0x03,0x04,0x05,0x06,0x07,
                               0x08,0x09,0x0a,0x0b,0x0c,0x0d,0x0e,0x0f];
const IV:         [u8; 12] = [0x00,0x00,0x00,0x01,0x00,0x03,0x00,0x42,
                               0x00,0x00,0x00,0x01];
const AAD:        [u8;  7] = [0x06,0xde,0xad,0xbe,0xef,0x00,0x42];
const PLAINTEXT:  [u8;  5] = [0x02,0x00,0x10,0x20,0x30];
/// Ciphertext (5 bytes) followed by the 4-byte GCM tag.
const CIPHER_TAG: [u8;  9] = [0x20,0xc3,0x51,0x50,0xdb,0x54,0x1d,0xbc,0x33];

#[test]
fn compat_aes_gcm4_encrypt_matches_node_oracle() {
    let out = encrypt(&KEY, &IV, &AAD, &PLAINTEXT);
    assert_eq!(
        out, &CIPHER_TAG[..],
        "Rust AES-128-GCM-4 encrypt must produce output byte-identical to the Node oracle",
    );
}

#[test]
fn compat_aes_gcm4_decrypt_matches_node_oracle() {
    let out = decrypt(&KEY, &IV, &AAD, &CIPHER_TAG)
        .expect("decrypt must accept the Node oracle ciphertext");
    assert_eq!(
        out, &PLAINTEXT[..],
        "Rust AES-128-GCM-4 decrypt must recover the original plaintext",
    );
}
