// SPDX-License-Identifier: AGPL-3.0-only
//
// Generate the AES-128-GCM-4 known-answer vector that
// `tests/crypto.rs` uses as its oracle. Run once from this directory:
//
//     node gen_vectors.mjs
//
// The script is deterministic — the same inputs always produce the
// same outputs, so re-running is safe and the Rust constants stay
// stable. Inputs are hard-coded to the values the spec §7.11
// compatibility test #1 calls out: a deterministic
// (key, iv, aad, plaintext) tuple that exercises the same Node
// `crypto` API the live sauce4zwift client uses
// (`zwift.mjs:1092-1106`).
//
// The script is checked in for reproducibility but is not invoked
// from CI; see `crates/zwift-relay/tests/fixtures/README.md`.

import * as Crypto from 'node:crypto';

// Deterministic inputs. 16-byte key, 12-byte IV (matches a real
// RelayIv { Relay, TcpClient, conn_id: 0x0042, seqno: 1 }
// → [0,0, 0,1, 0,3, 0,0x42, 0,0,0,1]).
const key = Buffer.from([
    0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07,
    0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f,
]);
const iv = Buffer.from([
    0x00, 0x00, 0x00, 0x01, 0x00, 0x03, 0x00, 0x42,
    0x00, 0x00, 0x00, 0x01,
]);
// 7-byte AAD: a Header { flags = RELAY_ID|CONN_ID, relay_id = 0xDEADBEEF,
// conn_id = 0x0042 } per `zwift.mjs:1112-1135` encode rule.
const aad = Buffer.from([
    0x06,                         // flags
    0xDE, 0xAD, 0xBE, 0xEF,       // relay_id BE u32
    0x00, 0x42,                   // conn_id  BE u16
]);
// 5-byte plaintext: TCP envelope `[2, hello?0:1=0, 0x10, 0x20, 0x30]`.
const plaintext = Buffer.from([0x02, 0x00, 0x10, 0x20, 0x30]);

const cipher = Crypto.createCipheriv('aes-128-gcm', key, iv, {authTagLength: 4});
cipher.setAAD(aad);
const cb1 = cipher.update(plaintext);
const cb2 = cipher.final();
const tag = cipher.getAuthTag();
const ciphertextWithTag = Buffer.concat([cb1, cb2, tag]);

const hex = (b) => b.toString('hex');

console.log('// AES-128-GCM with 4-byte tag, generated by gen_vectors.mjs');
console.log(`// node ${process.version}`);
console.log('');
console.log(`pub const KEY:        [u8; 16] = hex!("${hex(key)}");`);
console.log(`pub const IV:         [u8; 12] = hex!("${hex(iv)}");`);
console.log(`pub const AAD:        [u8;  7] = hex!("${hex(aad)}");`);
console.log(`pub const PLAINTEXT:  [u8;  5] = hex!("${hex(plaintext)}");`);
console.log(`pub const CIPHER_TAG: [u8;  9] = hex!("${hex(ciphertextWithTag)}");`);
console.log(`//                              ciphertext (5) || tag (4) = 9 bytes`);
